### ISSUE TITLE
External links don't open

### ISSUE THREAD

**Issue by gombosg** [mdh34/quickDocs#43] opened 2018-06-14 10:01 UTC
Hi!

I'm using the Flatpak version of QuickDocs on Fedora 28. Problem is that external links don't open (e.g. in the default browser). No error message on command line.

I also built the app from source (to see if this is some Flatpak sandboxing error) - it's not working there either.

**Comment by mdh34** [comment] 2018-06-16 14:54
I can confirm this, I'll have a look to see if I can find the cause

**Comment by mdh34** [comment] 2018-06-17 14:53
Fixed in https://github.com/mdh34/quickDocs/commit/cb065e4be416332384aa40a982c67ea634f9eecb

**Closed by mdh34** 2018-06-17 14:53 UTC
Labels: bug

**Comment by gombosg** [comment] 2018-06-18 07:56
Thanks! I updated the Flatpak package to 2.0.5.
It opens external DevDocs links in the same window, which is kind of OK (maybe an external browser would be better to not break the documentation viewing experience) but I can't go back, clicking on the back button brings me a blank page.

**Comment by mdh34** [comment] 2018-06-19 14:40
Opening links in the external browser is now implemented as of https://github.com/mdh34/quickDocs/commit/dcfc0199c5fb0fa2c8ce3a5ff085c9af2bde38f3

**Comment by gombosg** [comment] 2018-06-20 07:02
Tested, works perfectly now!
